apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-crud-backend
  namespace: dotnet-app-gcp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-crud-backend
  template:
    metadata:
      labels:
        app: dotnet-crud-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/iron-handler-471307-u7/dotnet-crud-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: dotnet-crud-config
              key: ConnectionStrings__DefaultConnection
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-proxy:2.8.0
        args:
          - "iron-handler-471307-u7:us-central1:dotnet-crud-db"
          - "--port=1433"
        ports:
          - containerPort: 1433
        securityContext:
          # The Cloud SQL Proxy requires an unprivileged user
          runAsNonRoot: true
        resources:
          limits:
            cpu: 100m
            memory: 128Mi