apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-crud-config
  namespace: dotnet-app-gcp
data:
  ConnectionStrings__DefaultConnection: "Server=127.0.0.1,1433;Database=ProductDb;User Id=dotnetapp;Password=DotNetAppPassword_123;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=True;Connection Timeout=30;"
